### ISSUE TITLE
Upgrade to JLine 2.13 breaks integration with org.fusesource.jansi.AnsiOutputStream

### ISSUE THREAD

**Issue by lanouettea** [jline/jline2#243] opened 2016-05-06 13:40 UTC
I have been working on a JavaFX application which is running on top of Karaf 3.0.2 (Which uses Jline 2.11). I developed a JavaFX terminal console connected to the Karaf console inside a JavaFX TextArea. In order to achieve this, the console out and err streams are piped through a AnsiOutputStream, which is a class from jansi, but provided with JLine. 

The AnsiOutputStream strips the Ansi codes from the terminal output, which is pretty useful for a clean output without having to manage text decorations. But more useful than this is the fact that it decodes the actual ansi codes and call methods like processCursorToColumn, processCursorLeft, etc. from the corresponding codes. 

The ConsoleReader class from 2.11 used to send ansi codes to manage cursor positions. However, the version 2.13 seems to have replace those by character codes. For example, if I send the character "J" to the console. I will receive "^h", then "J", while I used to receive Ansi cursor reposition instead of the backspace (^h). 

I don't see anyone else complain about this, so I guess this is not a game-breaker for many, but it seems to me that this is a regression to a class embedded inside the library that used to provide useful functions.

**Comment by bdw429s** [comment] 2016-05-09 04:56
I think this is the same issue I am seeing just now after upgrading to JLine 2.14.1 to get the fix for https://github.com/jline/jline2/issues/177
I used to send my own ANSI formatting via the `reader.print()` method for applying formatting or manipulating the cursor.  Now all the escape codes are being printed to the console instead. This completely breaks my CLI app as all the formatting is gone in favor of the raw ANSI escape codes being printed to the screen.

How do I get my ANSI formatting to be obeyed @gnodet ?

**Comment by bdw429s** [comment] 2016-05-09 05:02
Looks like this is a possible duplicate of https://github.com/jline/jline2/issues/205 ?

**Comment by gnodet** [comment] 2016-12-02 09:16
Closing as a duplicate of #205

**Closed** 2016-12-02 09:15 UTC
